# Generated by Django 6.0.5 on 2026-05-28 22:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.FileField(blank=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'jpg', 'jpeg'])], verbose_name='Icon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_communities', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscibed_comunities', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is closed')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Is pinned')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views count')),
                ('replies_count', models.PositiveIntegerField(default=0, verbose_name='Replies count')),
                ('last_active', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Last active')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_topics', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.community', verbose_name='Community')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('content', models.TextField(verbose_name='Content')),
                ('likes_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Likes count')),
                ('image', models.ImageField(blank=True, upload_to='posts/images/%Y/%m/%d/', verbose_name='Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Liked by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.post', verbose_name='Parent post')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['slug'], name='forum_commu_slug_e9e6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['community', '-is_pinned', '-last_active'], name='forum_topic_communi_bc6ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['topic', 'parent', 'created_at'], name='forum_post_topic_i_fa300a_idx'),
        ),
    ]
